{% set pypi = "libarchive-c" %}
{% set name = "python-libarchive-c" %}
{% set version = "2.9" %}
{% set sha256 = "9919344cec203f5db6596a29b5bc26b07ba9662925a05e24980b84709232ef60" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi[0] }}/{{ pypi }}/{{ pypi }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Add-zstd-support.patch

build:
  number: 0
  script:
  - set PYTHONHASHSEED=0  # [win]
  - export PYTHONHASHSEED=0  # [not win]
  - "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  host:
    - python
    - setuptools
  run:
    - libarchive
    - python

test:
  files:
    - test/hello_world.xar
  imports:
    - libarchive
  commands:
    - python -c "import libarchive; libarchive.extract_file('test/hello_world.xar')"  # [not win]
    - python -c "import libarchive; libarchive.extract_file('test\\hello_world.xar')"  # [win]

about:
  home: https://github.com/Changaco/python-libarchive-c
  license: CC0-1.0
  summary: Python interface to libarchive

extra:
  recipe-maintainers:
    - bollwyvl
    - mingwandroid
    - ocefpaf
