# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fdodnjISl0XJLFvPmW3lBJpI8fwB+kRW4x4JrzTWUXNK5Bonjz1HilWtTmR2wRbGgdQSEKVRgHuyl/HNGfhBkn/jEG4PN7VkYSmpGUsrlCLaP8E/xSAF4P7/vKk4jJvVVeAc0Pd/4UDQdj390N4frWGlZxpzwLTkSL81A+O0fCdELpWwt0s8GJroz8esqPXdzo1cDY6i5UuohD+UdcSOeb8xuGdMLvaY9mlPkJ19lPVhYrC6iS6ZBsFHATmB3csvF0JBJNrJYSXnmQ4GPxG8ZWmC38/dfHDTdHOjjrpY3F/c8Ds8CN3HVITb9u3rFnZ1MncdsHDOdIbPY2tMkArgRKnHdmyyHWZ0fdEQHAOaNhEwJheb4FVsdh+pr/ooMvmHdmMlPKz3m1JM9FVN/NFC5KNxv+aoVVSYmrtMSkPjbhe87VAD2TgArjT0sjqgO3EH/GQMIrvXnr7spSPOhjZObDss/ZaD8fOgOwcr5n+cu/nU6ZBzsvI6EejmVrwcm/q/rBgWp4+hkFtyg516wTViIeHlHUAjQf6VRsfFfbAceCI92lyHgUxKYKLYwobQLiCyh4mDbRMjoDb8257kdveRY69aAmO3RIXGunPLPa+XccRviPyZTObnjtPeuGBEtNqZHuWMvsmmLJN1KFBKmp+NDcAha9FXMe7uXQ7U5vFBp1U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
