travis:
  secure:
    BINSTAR_TOKEN: f0TqZYTz4Da9BxdhDNV+RfI7Mx/ldsrraPkhCr+0sIuhZC2gunIJdDv6fZkVTBMUQNg5wtXmWEv/KaPfccx9q2280YreQcPcNuXU97FS872XA49RJS33oVyEKH5K/Jy3E4QCwjqr8Dx93WPSXnUkWI0jwlvHNyTtjzzULY6GHRY6pYli0YC9NHclSmHV3wKxT5DLLfmUaiAFfOhhS5lLqvjW887Rs5+alsV5BdV6bsYTbDO1aUsx5t6IRVewOOCIfPscpRACH1oAsksQ9493nwoh2XS42YsraKtAUru463pPic7pFvC6qo0kU+wN8UIzAjgUU9olXWb/fifP+7hMfP3K0FC6Q5wLl+S5AbV0L4qpWK78ursWoWa7cf68S1MMx8ey5M10zCRhQWER1YyVXw+JJmjhinLhin9btjbs44O5l4Ei/IAn1+0KfVtj1yvDUjIxBKnddyCSbHJ3wEZq4vkIXR5u8m2nH6ofj72vx3ngzMU7TsKxW7UX2xRv3HiE5PJix8WxGSDxRemgbUXTgMQ4yl/wWltZQzH7Bku0vpANgC/AQ44bIfLyNCcNkEgIyXrDBhzuZtEuYtOhAgo0vuwi3mjQx9+NZAiguGyeV3T6vJ+/QSJ7v3U6JdF33ISzs+RO+hmofYw8NaoJPqcQ6slpI1EIO/Kc42kU+BK2YOs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
