travis:
  secure:
    BINSTAR_TOKEN: fdodnjISl0XJLFvPmW3lBJpI8fwB+kRW4x4JrzTWUXNK5Bonjz1HilWtTmR2wRbGgdQSEKVRgHuyl/HNGfhBkn/jEG4PN7VkYSmpGUsrlCLaP8E/xSAF4P7/vKk4jJvVVeAc0Pd/4UDQdj390N4frWGlZxpzwLTkSL81A+O0fCdELpWwt0s8GJroz8esqPXdzo1cDY6i5UuohD+UdcSOeb8xuGdMLvaY9mlPkJ19lPVhYrC6iS6ZBsFHATmB3csvF0JBJNrJYSXnmQ4GPxG8ZWmC38/dfHDTdHOjjrpY3F/c8Ds8CN3HVITb9u3rFnZ1MncdsHDOdIbPY2tMkArgRKnHdmyyHWZ0fdEQHAOaNhEwJheb4FVsdh+pr/ooMvmHdmMlPKz3m1JM9FVN/NFC5KNxv+aoVVSYmrtMSkPjbhe87VAD2TgArjT0sjqgO3EH/GQMIrvXnr7spSPOhjZObDss/ZaD8fOgOwcr5n+cu/nU6ZBzsvI6EejmVrwcm/q/rBgWp4+hkFtyg516wTViIeHlHUAjQf6VRsfFfbAceCI92lyHgUxKYKLYwobQLiCyh4mDbRMjoDb8257kdveRY69aAmO3RIXGunPLPa+XccRviPyZTObnjtPeuGBEtNqZHuWMvsmmLJN1KFBKmp+NDcAha9FXMe7uXQ7U5vFBp1U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
